### ISSUE TITLE
Thebe "activate" button on website

### ISSUE THREAD

**Issue by paulmasson** [sagemath/website#106]
The button to make documentation examples live is meant to be active only in the context of Jupyter notebooks, but appears on website pages. Clicking it then clicking "run" after an example leads to an error message and makes the website appear broken.

Is this something that should be fixed here or in SageMath? Was the integration of Thebe on https://trac.sagemath.org/ticket/20690 done correctly? Should I move this discussion to sage-devel?

**Comment by haraldschilly** [comment]
this repository is for the sagemath website, not the documentation. closing this, dup of https://github.com/sagemath/documentation/issues/12

and regarding "correct integration". the test for the jupyter context is `if (window.location.protocol.startsWith('http')) {` which is definitely not enough.
