### ISSUE TITLE
Wrong link in the main home page

### ISSUE THREAD

**Issue by egourgoulhon** [sagemath/website#136]
Hi, 

The anchor "Mathematical Computation with Sage" at the entry page [http://www.sagemath.org/](http://www.sagemath.org/)  should be updated: the correct link is [http://sagebook.gforge.inria.fr/english.html](http://sagebook.gforge.inria.fr/english.html).

Best wishes,

Eric.

**Comment by haraldschilly** [comment]
thank you

**Comment by haraldschilly** [comment]
I see, the "german translation" link is also broken, as well as it is on http://sagebook.gforge.inria.fr/english.html

do you happen to know where it is now?

**Comment by egourgoulhon** [comment]
Sorry I don't know about the correct link about the German version...

**Comment by haraldschilly** [comment]
ok, I'll contact someone on that page
