### ISSUE TITLE
link to changlog for version 6.4 not working

### ISSUE THREAD

**Issue by petergthatsme** [sagemath/website#14]
On the main site http://www.sagemath.org/index.html the link to the change log:
http://www.sagemath.org/mirror/src/changelogs/sage-6.4.txt
... does not work.

**Comment by haraldschilly** [comment]
also fix link to changelog at `/development.html` ... and my general plan is to copy over all changelogs into a dedicated /changelogs subdirectory. The only missing piece is an automatically generated index file for them.

**Comment by petergthatsme** [comment]
I would propose to just remove the changelog link from the front page altogether, given that it often (mostly always?) does not work.

**Comment by slel** [comment]
Fixed by commit https://github.com/sagemath/website/commit/0f9a7cc481f33a1db2543574736a67a2ea21b6f6
Please close.
