### ISSUE TITLE
Quickstart page is obsolete

### ISSUE THREAD

**Issue by egourgoulhon** [sagemath/website#151]
The [Quickstart page](http://www.sagemath.org/tour-quickstart.html) (accessible from the Tour menu of Sage main page) is obsolete and misleading for newcomers, see https://ask.sagemath.org/question/43616/printing-_sage_var_x-instead-of-x/.

**Comment by egourgoulhon** [comment]
Beside the pretty print mentioned in the ask.sagemath question, the `RealIntervalField` example is broken as well, since we have in Sage 8.3:

```
sage: R = RealIntervalField(100)
sage: a = R((-1,0)); a
-1.?
```

**Comment by abmclin** [comment]
I'd like to comment here that the Quickstart page still hasn't been updated and I was running the examples as a first-time user who just installed Sage 9.0 and noticed the same issues that initially had me concerned about whether my installation was working correctly.

**Comment by fchapoton** [comment]
This is now fixed.
