### ISSUE TITLE
Remove (or update) "Contributing to Sage" video

### ISSUE THREAD

**Issue by embray** [sagemath/website#158]
http://www.sagemath.org/development.html has a link to a very nice video hosted on Vimeo (the embedding is broken which could also be fixed, but read on...) of William giving a guide for newbies (both to Sage, and OSS development in general) on how to make a contribution to Sage.

Unfortunately this video is very outdated (8 years old, and I've personally never known @williamstein without a beard).  So perhaps the link should be removed lest some unwitting person spend 40 minutes learning information that is largely out-of-date.  Many of the generalities are still the same of course, but not the specifics.

Alternatively / additionally I'd be willing to help produce a new video on the subject.  But maybe in the meantime this one should still be taken down, or at least the page annotated with some warnings about the most out-of-date aspects of the video (in particular some of the URLs, and the use of Mercurial (RIP).

**Comment by haraldschilly** [comment]
I agree, and a new video would be great ...
