### ISSUE TITLE
Contributing to this project (Git Issues)

### ISSUE THREAD

**Issue by chippo1** [sagemath/website#181]
I was going through the Sage tutorials and noticed that some of the cut'n'paste examples don't work because of interfaces changes etc. I was going through
http://doc.sagemath.org/html/en/prep/Advanced-2DPlotting.html
when I decided to fix them.

I somehow ended up doing a 'git clone https://github.com/sagemath/website.git'. I got some stuff, but found that that plotting tutorial (mentioned above) was not among them. So looking at
https://github.com/sagemath/website/blob/master/README.md
I saw some stuff about --recursive and a git-clone line to cut'n'paste.

But it doesn't work (probably github changed procedure at some point). I figured out the correct new URL and fixed README.md. I also notice that this (now working) --recursive submodules stuff doesn't fetch the plotting tutorial :-( ! But first things first! Let me first commit, and push, and pull-request the error in README.md.

I committed the change and then tried:

git push https://github.com/chippo1/sagemath/website HEAD:master
remote: Not Found
fatal: repository 'https://github.com/chippo1/sagemath/website/' not found

Oops! And so to prove that I completely don't understand how this all works, I tried:
git push https://github.com/sagemath/chippo1/website HEAD:master
which worked equally well.

Sorry if this is an FAQ, but how do I push to a fork (for this website project)?

And, secondly, where should I be git-cloning from, to get the sources for
http://doc.sagemath.org/html/en/prep/Advanced-2DPlotting.html
and friends, so that I can fix them?

**Comment by saraedum** [comment]
> git push chippo1/sagemath/website HEAD:master
> remote: Not Found

Press the fork button on the repository (top right corner), then do `git remote add chippo1 https://…` (insert the clone URL of your fork repository). Then `git push chippo1 HEAD:master` should work. In any case, there are lots of tutorials on how to contribute to a github project that probably explain this better than I can.

**Comment by saraedum** [comment]
(sorry, didn't mean to close.)

**Comment by saraedum** [comment]
> And, secondly, where should I be git-cloning from, to get the sources for
http://doc.sagemath.org/html/en/prep/Advanced-2DPlotting.html
and friends, so that I can fix them?

This can be found here https://gitlab.com/sagemath/sage/blob/develop/src/doc/en/prep/Advanced-2DPlotting.rst

**Comment by saraedum** [comment]
This interface is automatically tested with every release of SageMath, so the commands should actually work btw.

**Comment by saraedum** [comment]
I believe that we can close this issue now. The issues are not really related to sagemath website (even though they show up on sagemath.org.)

**Comment by kcrisman** [comment]
@chippo1, for what it's worth, those tutorials were created as part of a workshop, and so it would be helpful to make an edit that keeps the integrity of that, while noting what has been changed for interface reasons.  If you make a ticket on the Trac site, please cc: 'kcrisman' and I will get updates to help.

**Comment by chippo1** [comment]
@kcrisman, of course. And, maybe the tutorials are fine. @saraedum already alerted me to the fact that the examples in the tutorials are automatically tested with each new release.

I noticed that the tutorials (on the website) claimed to be part of the sage-8.9 documentation, while mine was (whatever comes with ubuntu) sage-8.6 (where some of them didn't work without changes). I'm currently compiling git-latest (--with-python=3), which is close to 9.0.beta4. I'll test the tutorials with that - surely we want them to work best with future versions rather than historical versions?

And @kcrisman , IFF any changes are actually needed, I'll email you before I make a trac-ticket.

**Comment by kcrisman** [comment]
@chippo1 No worries, just open the ticket and cc: there - we try to keep as much development conversation public as possible :smiley:
