### ISSUE TITLE
Gambit library (Sagemath v9) : it doesn’t have enough library

### ISSUE THREAD

**Issue by Quocanh90-r** [sagemath/website#192]
+ I use Win 10 64bit, Python 3.8.2
+ I want to use Python scripting API with Gambit 15.1
+ I failed to install as the instruction http://gambit.sourceforge.net/gambit15/build.html#build-python
+ I found out the facebook of Gambit (Gambit: Software Tools for Game Theory), it stated: “There is a set of Python bindings to the Gambit library and analysis algorithms. These bindings facilitate interfacing Gambit to the well-developed ecosystem of libraries in Python for scientific computation. In particular, Gambit is now included in SageMath (http://www.sagemath.org), an Open Source system for doing computational mathematics.”
+In the Sagemath, it informed ‘Since version 9.0 released in January 2020, SageMath is using Python 3.’
+ Gambit libraries is installed, however, it doesn’t have enough library. Please see it http://gambit.sourceforge.net/gambit15/pyapi.html 
  
![errror1](https://user-images.githubusercontent.com/64707635/81580330-34074500-93a5-11ea-8892-3b5c9da91c83.png)

+  Please give me some instructions to solve it asap.

**Comment by fchapoton** [comment]
This is not the place to ask such questions. Go to ask.sagemath.org
