### ISSUE TITLE
Critical: files.sagemath.org misconfiguration breaks downloading the sage mirror_list

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/website#194]
See https://groups.google.com/d/msg/sage-release/d8dVrQai_x8/U9haVP6jAQAJ

**Comment by haraldschilly** [comment]
is there a minimal example how to reproduce this?

**Comment by haraldschilly** [comment]
ok, well, I used `sage -ipython` and the snippet below to debug and fix this

```
>>> import urllib
>>> eval(urllib.urlopen('http://www.sagemath.org/mirror_list').read())
```

the problem is it's not https, which is universally enforced. it's disabled for this url now and hence there are no such security issues again. My suggestion is to update this url to `https://...`

**Comment by mkoeppe** [comment]
Thanks, that fixed it. I have created https://trac.sagemath.org/ticket/29735 (Improve sage mirror list download)
