### ISSUE TITLE
Sage Logo broken, used in wiki.sagemath.org and https://groups.google.com/forum/#!forum/sage-support

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/website#195]

**Comment by haraldschilly** [comment]
that happened in 9dfbbd24825577a37ba8dc5ce2d8e337383ed2cb → @fchapoton 

I'll move this one back, because it takes too much time to fix it in all locations (I don't even know where else it is used). In the future, we better don't move/rename prominent files that might be used elsewhere.

**Comment by mkoeppe** [comment]
How about adding a README to these directories on the server to document where certain files are used? @fchapoton

**Comment by fchapoton** [comment]
There is a new logo available for the wiki under the link

pix/logo_sagemath_wiki.png

**Comment by mkoeppe** [comment]
Have you tried contacting an admin of the wiki?
