### ISSUE TITLE
Remove or clarify role of src/mirror/metalinks.html

### ISSUE THREAD

**Issue by kcrisman** [sagemath/website#21]
src/mirror/index.html seems to have a lot of what is there, and although links like http://jambu.spms.ntu.edu.sg/sage/metalinks.html still work,  it's only linked from the *list* of mirrors (!) and isn't useful because everything is so old.

(Indeed, I didn't realize how much junk there is in this site.  All the src/inc/ shtml stuff is currently unused?)

**Comment by theaverageguy** [comment]
I would like to fix this.
Please guide me. Thanks.

**Comment by haraldschilly** [comment]
that's the blue print for re-creating a master mirror. i.e. beside the website, this code is also used to manage the file server and the mirrors, etc.
