### ISSUE TITLE
Video link broken for: Modeling in SageMath: Love, War, and Zombies

### ISSUE THREAD

**Issue by simonbagley** [sagemath/website#222]
The video link for 'Modeling in SageMath: Love, War, and Zombies', does not work in a Chrome browser.

**Comment by haraldschilly** [comment]
would this video be https://www.youtube.com/watch?v=z3MAPweScz8 ?

**Comment by kcrisman** [comment]
On Mon, Sep 6, 2021 at 8:09 AM Harald Schilly ***@***.***>
wrote:

> would this video be https://www.youtube.com/watch?v=z3MAPweScz8 ?
>
>
Most likely, yes; David was the one who often used that topic.

**Comment by simonbagley** [comment]
@haraldschilly yes that does indeed look like the video in question.

**Comment by simonbagley** [comment]
Whoops! I closed this in error. I think it should only be closed when the link on the website works.

**Comment by subho951m** [comment]
@simonbagley Sir, I would like to give a try to fix the issue. Is the video link @haraldschilly posted the one which needs to be attached or is there any other video link?
Please guide me.

**Comment by subho951m** [comment]
@simonbagley Sir, I am facing difficulty in creating environment. I have cloned the repository but could not find `make` command. I am using windows 10 operating system.
Is there any other alternative to how I can set up environment in Windows 10?
Please help.

**Comment by simonbagley** [comment]
@subho951m yes the video @haraldschilly posted the link to is the correct one.
If you’re using Windows 10 I would suggest you use Windows Subsystem Linux (WSL) to install a suitable Linux environment (e.g. Ubuntu). The make command should work from this environment.

**Comment by subho951m** [comment]
@haraldschilly @simonbagley I used git to clone the website repository from Windows 10. Then I learned that the website should be run on Linux. So I used WSL feature of windows & downloaded Ubuntu 20.04.
I run `sudo apt-get install -y pybtex python-jinja2 python-markdown python-yaml`.
I installed python 2, pyinotify, xdtool, pep8, autopep8.
After doing all the above the following error was shown.

![Screenshot-1254](https://user-images.githubusercontent.com/88569334/143818129-76c5f562-0c38-4f23-ad42-67b142ddaba4.png)
![Screenshot-1255](https://user-images.githubusercontent.com/88569334/143818159-7a8d9fcc-db8a-4fe6-b11c-3e5e98eb000a.png)

Have I installed all the required packages for the website or should I add more?
Will I also have to install NQ8 images?
`pngnq -v -f -s 64 index_icons.png`.

**Comment by simonbagley** [comment]
@subho951m I don’t know, as I have never done a build, but maybe you should try a different shell? Possibly there’s some incompatibility with bash.

**Comment by haraldschilly** [comment]
Hi, what's going on with this issue? Is the video fixed or not? Is it relevant?

I also don't know anything about sage on windows.

**Comment by kcrisman** [comment]
I believe that @subho951m is trying to actually create the website by using make - notice that the cloned repo in the screenshot is the website one.  But I don't think that is possible to do.  @subho951m it would be easier to do this on the GitHub website and fix the link in a branch there, if you have any experience attempting that.  It would be a pretty trivial fix.

**Comment by subho951m** [comment]
@haraldschilly Sir I am using Ubuntu 20.04 on virtual machine. I tried a lot but could not fix the following problem. Please help.
![Screenshot (1)](https://user-images.githubusercontent.com/88569334/144220477-77007fc0-52ec-4f9a-8c53-bb4f9201f499.png)

**Comment by subho951m** [comment]
@haraldschilly It's showing problem in render.py .

**Comment by dimpase** [comment]
fixed by #227
