### ISSUE TITLE
rename Sage -> SageMath

### ISSUE THREAD

**Issue by haraldschilly** [sagemath/website#30]
There is a variable for the name in https://github.com/sagemath/website/blob/master/conf/config.yaml

Use it everywhere possible and update it.

**Comment by haraldschilly** [comment]
commit 2d76c11f966b5a4a4121c is the first one changing a lot of plain "Sage" strings to the `{{ sage }}` template variable and setting the sage variable to "SageMath". works fine, maybe there are still subtle errors.

**Comment by nathanncohen** [comment]
Isn't this solved?

**Comment by haraldschilly** [comment]
The commit is rather huge & boring one, but is there something I did miss? I kept it open in case something comes up. But so far, it looks good :smiley:

**Comment by koffie** [comment]
I guess this can be closed after nothing coming up for two years.

**Comment by haraldschilly** [comment]
ok
