### ISSUE TITLE
Footer is not looking good. and some button links are broken here which is not user friendly.

### ISSUE THREAD

**Issue by withgaurav** [sagemath/website#441]
![image](https://user-images.githubusercontent.com/76643106/209569197-bdcfa2fb-a1b9-41f5-a5fa-dc8cc4b9f257.png)

**Comment by Pushkarmondal** [comment]
hey i am somehow able to fix footer....
<img width="1440" alt="Screenshot 2023-02-26 at 6 05 13 PM" src="https://user-images.githubusercontent.com/116779860/221410980-81413217-4880-4504-9fce-740ed67e867b.png">

**Comment by Pushkarmondal** [comment]
please look into this

**Comment by Jyoticharan** [comment]
I am really interested to work over this issue please assign me the issue

**Comment by haraldschilly** [comment]
there are no broken parts in the footer right now, hence I'm closing this
