### ISSUE TITLE
automatically configure version information

### ISSUE THREAD

**Issue by haraldschilly** [sagemath/website#481]
As far as I understand new releases trigger integrating release notes. That's cool, but what I still do manually is [updating this file](https://github.com/sagemath/website/blob/master/conf/config.yaml) (2x version and 1x ISO date)

This could be automated as well (reading in the yaml, fixing these 3 fields, then saving it)

/cc @soham30rane @kwankyu

**Comment by soham30rane** [comment]
So what we could do is
 - Create a new `.py` script which will fetch latest releases, determine the most recent stable release and update the [config file](https://github.com/sagemath/website/blob/master/conf/config.yaml)
 - We could run the script it in [this workflow](https://github.com/sagemath/website/blob/master/.github/workflows/generate_changelog.yml)
 
 Works ?

**Comment by kwankyu** [comment]
I think adding the function to https://github.com/sagemath/website/blob/master/scripts/create_changelog.py is simpler.

**Comment by soham30rane** [comment]
Okay, will work on it
