### ISSUE TITLE
zulip -- the main discussion forum for sage these days is zulip, but it could be easier to find on the website

### ISSUE THREAD

**Issue by williamstein** [sagemath/website#482]
Add maybe "Zulip Chat" here:

<img width="406" alt="image" src="https://github.com/user-attachments/assets/dfd753a2-0876-4ae7-ab6c-8e1cff362ff2">

and maybe also here:

https://www.sagemath.org/help-groups.html

Zulip is mentioned in a dropdown menu:

<img width="417" alt="image" src="https://github.com/user-attachments/assets/83cee330-7c33-4efd-8d26-558730c6906f">

However, that menu is only visible or searchable if you hover your mouse over it, e.g., doing control+f and searching doesn't find anything about chat or zulip:

<img width="1559" alt="image" src="https://github.com/user-attachments/assets/bb4aa691-2cc0-4fab-be87-eb774760398c">

Anyway, just adding one little extra link under Help/Documentation would pretty much solve this problem.

Possibly also relevant is that the Jupyter dev community recently voted to make zulip their official dev/support chat system, and they've been taking various steps to make Zulip easier to find from their websites...

**Comment by AdityaK1729** [comment]
Hi, I am willing to fix this

**Comment by AdityaK1729** [comment]
Do we need to add that right next to all the things mentioned here, or as a sublink inside of one of those (or both)

**Comment by williamstein** [comment]
Thanks!  I think both:

- `Video · Forums · Tutorial · FAQ · Questions? ` --> `Video · Zulip Chat · Forums · Tutorial · FAQ · Questions?`

then also in https://www.sagemath.org/help-groups.html and https://www.sagemath.org/development-groups.html

Those videos linked to in the video link (i.e., https://www.sagemath.org/help-video.html) are really, really old!

**Comment by AdityaK1729** [comment]
Inside the page adding this works?
```
Zulip-Chat
---
Sage Zulip
- zulip -- online
- If you have problems subscribing, contact us.
```
this same thing on both the forementioned pages, works or not?

**Comment by williamstein** [comment]
Looks good to me..
