### ISSUE TITLE
add NFS grant OCI-1147247

### ISSUE THREAD

**Issue by haraldschilly** [sagemath/website#50]
add

> Grant No. NSF OCI-1147247 (2012 — 2016) Collaborative Research: SI2-SSE: Sage-combinat:
> Developing and Sharing Open Source Software for Algebraic Combinatorics

with a link to http://www.nsf.gov/awardsearch/showAward?AWD_ID=1147247

to development-ack.html

**Comment by VinaySingh035** [comment]
@haraldschilly  where exactly would you like the link to be present on the above mentioned page.
And at last what should be the `text` referring that link?

**Comment by haraldschilly** [comment]
Well, make something up for the text? I don't know where it's best, chronologically next to the other grants sounds good.

**Comment by VinaySingh035** [comment]
As I saw the other grants and I guess `Grant No. 1147247` will be the best as it is similar to the previous grants.
So, gonna do it like that only.

**Comment by haraldschilly** [comment]
perfect :+1: 

in case you already have a local repository, make sure to pull in my last changes from earlier today. also, don't hesitate too much in doing such changes. making small fixes (moving the entry a bit up or down, etc.) to an existing changeset is much easier, than having to talk about it too much.

**Comment by VinaySingh035** [comment]
oh yes Thanks for that. :+1:

**Comment by theaverageguy** [comment]
@haraldschilly Can be closed. :)
Also, where are the issues reported for the sage repo? I can't find them. I would like to fix a good number of bugs before introducing myself as a GSoC participant.

**Comment by haraldschilly** [comment]
well, I fear this is a misunderstanding. this here is just the website, that's rather unrelated and independent of the sagemath code ...

the sage repository is here: http://trac.sagemath.org/

to get started with sage dev, here is our intro guide: http://doc.sagemath.org/html/en/developer/index.html

**Comment by haraldschilly** [comment]
but well, it's good to see that you try to work on small issues and that you are capable to do so

**Comment by theaverageguy** [comment]
No it is no misunderstanding. I very well understand this is the website. I also know about the repo for Sage and I did set it up already. I was just asking for the issues list. I am working on it today. :)
