### ISSUE TITLE
add link to jobs page from the menu

### ISSUE THREAD

**Issue by haraldschilly** [sagemath/website#51]
add a menu link pointing to http://wiki.sagemath.org/jobs

**Comment by VinaySingh035** [comment]
@haraldschilly  should I just add the link of `jobs` at the end of the ``` Links ```  subheading in the menu listing.

**Comment by haraldschilly** [comment]
Well, find a good spot for it! The contact part should be at the end, i would rather put it next to the wiki link?

**Comment by Jeevan-Kiran-Lenka** [comment]
Hey! I would like to work on it

**Comment by haraldschilly** [comment]
The page is here https://wiki.sagemath.org/jobs but I don't think anyone maintains it
