### ISSUE TITLE
redirect /report-issue to where users should report issues

### ISSUE THREAD

**Issue by haraldschilly** [sagemath/website#52]
should it be ask.sagemath?

**Comment by nathanncohen** [comment]
I think that it should. Can I make a pull request?

**Comment by haraldschilly** [comment]
Uhm, I think we should think this through first. When you look into the header, there is a "report bugs" link. It points to the wiki. The wiki points back to this report-issue link. Reminds me of https://youtu.be/JtEkUmYecnk

**Comment by nathanncohen** [comment]
> Uhm, I think we should think this through first. When you look into the header, there is a "report bugs" link. It points to the wiki. The wiki points back to this report-issue link. Reminds me of https://youtu.be/JtEkUmYecnk

We should have a page in our developer's manual that explains all
this. Then, we should have a link on the websites that redirects
there.

This is for the 'report a bug' link. It should probably be "write to
sage-devel" (asking newcomers to request a trac account+create a
ticket directly is too tough for a first time).

For the "get help" link, it should probably be "asksage" or sage-support indeed.

Nathann

**Comment by kcrisman** [comment]
> This is for the 'report a bug' link. It should probably be "write to
sage-devel" (asking newcomers to request a trac account+create a
ticket directly is too tough for a first time).

No no, I think that the point was that "report a bug" should be super easy.  That was the idea behind the spreadsheet.  So ask.sagemath is appropriate - but maybe we could change the name of the link to "have a question or possible bug?" or something.

Maybe this would also benefit from more voices, since I have a feeling that there is an optimum we haven't reached yet.  But I do recall a discussion moving away from the spreadsheet, since it wasn't very well attended.

**Comment by nathanncohen** [comment]
> No no, I think that the point was that "report a bug" should be super easy.

Right now it is super easy, the only trouble is that nobody goes
through the reports, answers the guys nor solves the problem.

So this does not work, and for as long as we do nothing people waste
their time reporting things.

Any way out is good for me, the statu quo is not.

Nathann

**Comment by kcrisman** [comment]
>
>
> Any way out is good for me, the statu quo is not.
>
>
:+1:

**Comment by nathanncohen** [comment]
What about doing this:
- Add a "Ask a question?" link in the "Help" menu toward asksage
- Add a "Report a Bug" link in the "Links" section toward sage-devel (here neither 'Help' nor 'Development' seems totally appropriate)
- Remove "Report a problem/About bugreporting/Bugtracker" from the Links menu. We can add a "Trac server" in the "developerment" menu to replace the "bugtracker" link.

Nathann

**Comment by nathanncohen** [comment]
Guys?

**Comment by haraldschilly** [comment]
just about the top header: what about removing "report bugs" and changing the wording of "Ask" to "Questions?" ... it's actually kind of stupid that it says "Ask" there, when you do not know what "ask" is.

so, this is also :+1: to the "Ask  a question?" in the help menu and the other change in the dev menu.

**Comment by nathanncohen** [comment]
Okay, I'll be implementing all this in a second then.

**Comment by nathanncohen** [comment]
Done at https://github.com/sagemath/website/pull/55

**Comment by kcrisman** [comment]
We can also still redirect report-issue rather than changing sagenb, see https://groups.google.com/forum/#!topic/sage-devel/Byyo2Vyi_0Q

**Comment by haraldschilly** [comment]
yes, I can do this right away. where should it point to? ask.sagemath.org ?

**Comment by kcrisman** [comment]
Oh, thanks!  I think that is as good a place as any.  Maybe while it is redirecting it can also say something about "search for your issue" first and not just the 'usual' message.
