### ISSUE TITLE
Link broken to complete documentation download

### ISSUE THREAD

**Issue by murrayE** [sagemath/website#59]
The link on http://www.sagemath.org/help.html to download the entire standard documentation as a compressed file is broken. At present, its target http://doc.sagemath.org/#download just gives a table-of-contents page with links to all the separate documents.

**Comment by haraldschilly** [comment]
Oh, that link shouldn't be there. Thank's for pointing that out.

Maintaining this download zipfile is a hassle and so far I don't see the point. When you have SageMath locally installed, you have the documentation. If you use it online, you can browse it. And if you are interested in downloading everything, you can grab the repository. Do you mind if I ask, in which category you belong and why you would want to download it?

**Comment by murrayE** [comment]
Sometimes I prefer to read the pdf documentation instead of the html pages included with Sage itself -- including when my local Sage is not running.

Guess I'll just have to get all the pdf's individually.

I do appreciate the hassle in maintaining the download zip file, though.


> On 15 Jun2015, at 4:37 PM, Harald Schilly <notifications@github.com> wrote:
> 
> Oh, that link shouldn't be there. Thank's for pointing that out.
> 
> Maintaining this download zipfile is a hassle and so far I don't see the point. When you have SageMath locally installed, you have the documentation. If you use it online, you can browse it. And if you are interested in downloading everything, you can grab the repository. Do you mind if I ask, in which category you belong and why you would want to download it?

——
Murray Eisenberg                                murray@math.umass.edu
Mathematics & Statistics Dept.       
Lederle Graduate Research Tower      phone 240 246-7240 (H)
University of Massachusetts                
710 North Pleasant Street                 
Amherst, MA 01003-9305

**Comment by haraldschilly** [comment]
Hi @murrayE ... as I wrote, you can actually download everything in a zip file. It's just not neatly separated by language and documentation type, but the whole package. Here is the [link to the archive](https://github.com/sagemath/documentation/archive/gh-pages.zip).
