### ISSUE TITLE
why does /documentation/ work?

### ISSUE THREAD

**Issue by haraldschilly** [sagemath/website#60]
How is it possible that http://www.sagemath.org/documentation/ works? :open_mouth:  
Seems like GitHub automagically redirects to sub-projects of an organization, in this case the gh-pages branch of sagemath/documenation ... This indeed opens up new possibilities. :black_joker:

**Comment by theaverageguy** [comment]
Ummm this is not an issue I believe @haraldschilly ?

**Comment by haraldschilly** [comment]
is it, or isn't it?

**Comment by theaverageguy** [comment]
Updated the comment.
