### ISSUE TITLE
Add changelog for Sage 6.2

### ISSUE THREAD

**Issue by slel** [sagemath/website#63]
The missing changelog can be copy-pasted from
https://groups.google.com/d/topic/sage-announce/hrgTU51lxVw/discussion
and should become a text file at
http://www.sagemath.org/changelogs/sage-6.2.txt

**Comment by VinaySingh035** [comment]
@slel  do  we have to paste the whole thing from that mail of google group you haver mentioned above.
from line 3 `Sage 6.2 was released on 6 May 2014. It is available in` to the end?
as I would like to do this thing.

**Comment by slel** [comment]
Yes, that's correct. See examples at
http://www.sagemath.org/changelogs/sage-6.0.txt
http://www.sagemath.org/changelogs/sage-6.1.txt
etc. The only one missing is 6.2.

Related task: make it so that
http://www.sagemath.org/changelogs/
displays a list of links to these changelogs.

**Comment by haraldschilly** [comment]
Oh yes, the only thing to take care of is, that the text file doesn't have the stupid additional linebreaks from the email formatting. Then, just send a pull request with the new file!

**Comment by VinaySingh035** [comment]
@slel , @haraldschilly 
Please review the PR and let me know if something could be improved?
