### ISSUE TITLE
index.html file for src/changelogs

### ISSUE THREAD

**Issue by haraldschilly** [sagemath/website#67]
the changelogs need a dedicated (small) index.html file for the CDN ... which doesn't do things like that automatically.

**Comment by haraldschilly** [comment]
to answer the question from the other ticket: we can either link to the github repository (easy) or automatically create our own index page. I would suggest to create our own. For that, we have to sort the filenames by the version number (with corner cases) and insert this list of names/links into a template page to render it.

**Comment by haraldschilly** [comment]
http://www.sagemath.org/changelogs/ exists now and is sorted by version number

**Comment by slel** [comment]
@haraldschilly: by "the question from the other ticket" you mean https://github.com/sagemath/website/issues/58#issuecomment-167962693, right?

**Comment by haraldschilly** [comment]
yes
