### ISSUE TITLE
Language conversions don't work properly.

### ISSUE THREAD

**Issue by theaverageguy** [sagemath/website#77]
Not consistent with English page. All of them vary in number of tabs and text.

**Comment by kcrisman** [comment]
I'm not sure what you mean by "language conversions"; these are definitely not the full page and weren't necessarily intended to be.  That said, it would be nice to enhance some of these, but it would probably (to be realistic) have to be on a case-by-case basis.

**Comment by mrennekamp** [comment]
@theaverageguy Humans translate the pages...? Remove if this is case, please

**Comment by haraldschilly** [comment]
closing, confusing ticket
