### ISSUE TITLE
Sitemaps for documentation indexing

### ISSUE THREAD

**Issue by paulmasson** [sagemath/website#86]
@haraldschilly since you blacklisted /doc/ and /documentation/ more links are going directly to the desired subdomain doc.sagemath.org. I am noticing though that many items still relay on the manual redirection and are not getting updated in Google's index.

A friend and I wrote a JavaScript utility to create text-file listings of all files in a GitHub website filtered by extension with optional redirection from the default github.io location:

http://exploratoria.github.io/lib/github-api/sitemap.html

In order to speed up Google's indexing of the documentation, I would suggest a sitemap of all .html files in /documentation/html/ and all .pdf files in /documentation/pdf/. If you want me to create these sitemaps, I'm happy to submit a pull request for them. You of course would then need to submit them through Google's Webmaster Tools.

**Comment by haraldschilly** [comment]
@paulmasson hello, well, I don't know how to force an update. I noticed in those "indexing"graphs, that only in the past two days the google robot started to scan more pages. 

If you know how to do such a sitemap.xml, I'm happy to include it or submit it to webmaster tools. right now there is just a very rudimentary one, that's not really doing anything.

**Comment by paulmasson** [comment]
@haraldschilly Google accepts several formats of sitemaps, and I think the best one for the current situation is a simple text file listing full URLs. I've created three files in the pull request:

1) All .html files in documentation/html - this is probably the most useful one
2) All .pdf files in documentation/pdf
3) All .html files in documentation/pdf - really simple index files, don't know if you care about them

Take a look at the URLs. If you're happy about them, the merge and submit to Google. If you need to have anything altered let me known.

**Comment by haraldschilly** [comment]
ok, I'm merging it and testing what it does. I'm not sure though, if this will work, since the "website" is in www., but the sitemap points to the "documentation" hosted at doc.* . Maybe I should actually put that file online at doc.*

**Comment by paulmasson** [comment]
@haraldschilly I know it's only been a couple weeks, but I'm still seeing this message on lots of files:

`A description for this result is not available because of this site's robots.txt`

That means Google still isn't looking where we want it to look for the file, but still thinks it's in a loction you blacklisted.

What percentages of the three site maps are indexed as shown in Webmaster Tools? Thanks.

**Comment by haraldschilly** [comment]
so, the only really "interesting" graph there is, that the number of crawled pages went up significantly, and that the size of the index grew. before that, only fewer pages of the documentation were indexed. I think it's better now, but still on the wrong domain. 

www.sagemath.org: 6,823  Submitted,  2,729  Indexed // Total indexed	 4,588, Blocked by robots 4,686

doc.sagemath.org: 6,815  Submitted 2,714  Indexed // Total indexed	3,048, Blocked by robots 0

**Comment by slel** [comment]
In addition to redirecting  sagemath.org/doc/ to doc.sagemath.org/html/en/
we should also make sure to redirect sagemath.org/git-developer-guide/
to doc.sagemath.org/html/en/developer/ --- is that taken care of?

**Comment by haraldschilly** [comment]
No, and no idea how that guide ends up there. I think this should rather be an entry in the robots.txt?

**Comment by slel** [comment]
Relevant discussions on sage-devel and sage-combinat devel:

sage-devel: doc.sagemath.org gone from google
https://groups.google.com/d/topic/sage-devel/cCGobP2AgwM/discussion

sage-devel: Multiple versions of SageMath's documentation online
https://groups.google.com/d/topic/sage-devel/NJSAQTjhIWE/discussion)

sage-combinat-devel: Multiple versions of SageMath's documentation online
https://groups.google.com/d/topic/sage-combinat-devel/2CDGwe7C5mg/discussion

sage-devel: Multiple versions of SageMath's documentation online
https://groups.google.com/d/topic/sage-devel/qHC69E_8gNc/discussion
