### ISSUE TITLE
devmap broken

### ISSUE THREAD

**Issue by haraldschilly** [sagemath/website#90]
MarkerClusterer is missing, deprecated or updated?!

**Comment by slel** [comment]
Possibly relevant:

- https://github.com/tomchentw/react-google-maps/issues/255
- http://stackoverflow.com/questions/37180731/what-is-the-alternate-source-path-for-google-markerclusterer-js-library
- http://stackoverflow.com/questions/37276198/cluster-image-on-google-map-v3-is-broken
- http://stackoverflow.com/questions/37179980/markercluster-v3-stopped-working-properly
- https://wp-types.com/forums/topic/link-to-google-maps-code-repo-broken-for-map-images-etc/

**Comment by haraldschilly** [comment]
​well, I already fixed it, the root cause is that this googlecode page is
going away.
