### ISSUE TITLE
Ubuntu 16.04 support?

### ISSUE THREAD

**Issue by PallHaraldsson** [sagemath/website#94]
Implied by 14.04?

I'm not sure where to edit:

https://wiki.sagemath.org/SupportedPlatforms

and it's great that Ubuntu 8.04 is still supported, I just doubt that it is, ans still tested there..

I clicked on some links, for that one (and newer) and they are not convincing..

**Comment by haraldschilly** [comment]
It's a wiki page, so you have to log in with your account, the one from trac I think, and click the "edit" link.
