### ISSUE TITLE
"Spam was detected on your post, sorry for if this is a mistake"

### ISSUE THREAD

**Issue by louisgag** [sagemath/website#99]
Hi guys,
On the ask.sagemath website I am unable to leave any kind of comment to my post ( https://ask.sagemath.org/question/35596/export-notebook-output-to-html/ ) or to even post a new question. Can this be linked to this bug: "https://bugs.launchpad.net/openstack-community/+bug/1605929" ?
Cheers,
-Louis

**Comment by haraldschilly** [comment]
hello, I don't know much about the "ask page" and reporting a problem here is likely not being heard. 

/cc @nthiery  ... maybe you know how to deal with this or forward it appropriately.

**Comment by louisgag** [comment]
Hi thanks for the forward, this is the only place I've found a way to contact someone.

**Comment by kcrisman** [comment]
This isn't related to the Sage website.  Usually the only delay is that we do have some moderation in place for first-time posts, so someone has to green-light it.  In this case, I see you have made several comments, and there is nothing in the review queue, so I'm not sure why you'd be having problems.  I'll forward to our moderation crew - @haraldschilly this can be closed.
